---

- name: Restart rsyslog
  when: not ansible_check_mode
  become: true
  ansible.builtin.systemd:
    name: "{{ rsyslog_service_name }}"
    state: restarted

- name: Reload rsyslog
  when: not ansible_check_mode
  become: true
  ansible.builtin.systemd:
    name: "{{ rsyslog_service_name }}"
    state: reloaded
